spring.application.name=sample

spring.datasource.url=jdbc:postgresql://localhost:5432/sample
spring.datasource.username=sample
spring.datasource.password=sample

mybatis.configuration.map-underscore-to-camel-case=true
